### ISSUE TITLE
How to specify both ui types (BDD & TDD)

### ISSUE THREAD

**Issue by dschinkel** [sindresorhus/gulp-mocha#100]
I'm using gulp.  I'm running BDD and TDD tests..totally seperate from each other.  I've got the tests separated into a /bdd and /tdd folder.  I tried to add both types of "ui" in mocha options and it doesn't work that way I guess with gulp-mocha.  Does this mean I'll need to setup 2 separate gulp tasks, one specific to BDD and one specific to TDD then?  It'd be nice if I could just use one task to specify that I'm running both types of tests with the 'ui' option.

**Comment by sindresorhus** [comment]
Yes, you would need multiple gulp tasks. This is a Mocha limitation. Open an issue there if you feel strongly about it: https://github.com/mochajs/mocha

**Comment by dschinkel** [comment]
gotcha thanks for the verification!  Most people aren't really doing BDD & TDD both (IMO like they should be - but that's obviously a debate) so most examples out there default to either one.
