### ISSUE TITLE
expect('foo').equal('bar') throws an exception that is not being caught when dot reporter is used

### ISSUE THREAD

**Issue by op1ekun** [sindresorhus/gulp-mocha#103]
I have just started writing a spec and obviously I wanted to start from some smoke tests. Unfortunately I found a very annoying issue (topic says it all) while using `gulp-mocha` with `dot` reporter:

I have a following expectation:

```
expect('foo').equal('bar');
```

When I run it alone (using only `chai.excpert`) it produces:

```
AssertionError
Message:
    expected 'foo' to equal 'bar'
Details:
    showDiff: true
    actual: foo
    expected: bar
```

Excellent!

However when this expectation is wrapped with `describe` and `it` like this:

```
describe('foobar', function () {
    it('should foo with bar', function () {
        expect('foo').equal('bar');
    });
});
```

 and run in `mocha` I only receive:

```
  .
  1 failing
```

Out of curiosity I wrapped the expectation with `try catch` like this:

```
describe('foobar', function () {
    it('should foo with bar', function () {
        try {
            expect('foo').equal('bar');
        } catch(err) {
            console.log(err);
        }
    });
});
```

...and to my surprise it catched an exception, and obviously passed my test...

```
  { [AssertionError: expected 'foo' to equal 'bar']
  message: 'expected \'foo\' to equal \'bar\'',
  showDiff: true,
  actual: 'foo',
  expected: 'bar' }

  .
  1 passing (3ms)
```

I can't think of any use case where it should work this way :)

Oh BTW when I run test using mocha directly I get the expected result when I run mocha manually:

```
foobar
    1) should foo with bar


  0 passing (5ms)
  1 failing

  1) foobar should foo with bar:

      AssertionError: expected 'foo' to equal 'bar'
      + expected - actual

      -foo
      +bar

      at Context.<anonymous> (c:\dev\expect.test.js:8:27)
```

My environment:
Windows Server 2012 R2 Standard
node.js 0.10.40 (due to http://blog.nodejs.org/2015/07/09/node-v0-10-40-maintenance/)
mocha 1.21.5
chai 1.9.1
gulp-mocha 2.1.3

**Comment by op1ekun** [comment]
Is switched to gulp-spawn-mocha which works as expected.

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
