### ISSUE TITLE
Can't run React JSX tests

### ISSUE THREAD

**Issue by screendriver** [sindresorhus/gulp-mocha#107]
My source files import React components (*.jsx files).

``` js
import myComponent from './components/mycomponent'
```

`mycomponent.jsx` has the file extension jsx to indicate it's a React component. Unfortunately gulp-mocha tells me

``` sh
Error: Cannot find module './components/mycomponent'
```

At the command line everything works

``` sh
$ mocha --compilers js:babel/register test/*.js*
```

If I change my import to 

``` js
import myComponent from './components/mycomponent.jsx'
```

`gulp-mocha` works as well.

Is there a trick that I am missing? By the way: my `gulpfile` is named `gulpfile.babel.js` so I can write Gulp tasks in ES2015 and don't have to `require('babel/register')` manually.

**Comment by cliren** [comment]
Same issue here:

import "./some_file" // ./some_file.es6 works

gives the module not found error.

**Comment by HugoGiraudel** [comment]
I can also reproduce the issue. Set up a basic example here: https://github.com/HugoGiraudel/gulpfile-es6/pull/1.

Any idea @sindresorhus?

**Comment by elyseko** [comment]
I'm also having this issue. Any updates on this problem?

**Comment by ausi** [comment]
You can try to solve it by adding the following code to the top of your *gulpfile.babel.js*:

```js
import babel from 'babel/register';
babel({
  extensions: [".jsx"]
});
```

**Comment by elyseko** [comment]
Yes that worked! Thanks. One note - the version I'm using the import statement looked like:

```
import babel from 'babel-core/register';
```

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0 Just follow the Mocha guide for using Babel.
