### ISSUE TITLE
Passing node flags

### ISSUE THREAD

**Issue by louisbranch** [sindresorhus/gulp-mocha#11]
Is it possible to run gulp-mocha with a node flag as in: mocha --harmony ?

The flags for mocha are listed here: https://github.com/visionmedia/mocha/blob/master/bin/mocha#L28

**Comment by dschinkel** [comment]
I resolved this painful problem using the harmonize https://github.com/dcodeIO/node-harmonize.  Lets you programmatically add that flag.  And all I had to do I think was just npm install it and my problems went away with harmony flag issue with my tests.

**Comment by kbuildsyourdotcom** [comment]
Thank you, @dschinkel! That's what I was looking for :)
