### ISSUE TITLE
Domain expands into end callback

### ISSUE THREAD

**Issue by kpdecker** [sindresorhus/gulp-mocha#112]
When the `end` callback is made, the domain that is created by gulp-mocha expands into that callback. When combined with the no longer recommended [pattern](https://github.com/SBoudrias/gulp-istanbul/commit/0e5797b58be43a49891c78ea34e03f2ac132e4a8) of using `end` to call `done`, this causes the mocha error handler to catch all unhandled exceptions for any future gulp tasks.

Simple fix here is to call `d.exit()` prior to emitting the end event.

**Comment by kpdecker** [comment]
Actually it appears that not just explicit done handling causes this. Piping to writeReports under the new recommendation causes the same issue as that utilizes `end` as well.

When the stream is returned and the final pipe on the chain, this issue does not occur:

```
  return Gulp.src(testFiles())
      .pipe(plumber())
      .pipe(mocha());
```

**Comment by shellscape** [comment]
@kpdecker if this is still an issue please follow up with some info for us:

- node version
- npm version
- gulp-mocha version
- example tests and scripts to reproduce the problem

Cheers
