### ISSUE TITLE
gulp-mocha with gulp.watch causing error

### ISSUE THREAD

**Issue by lifehackett** [sindresorhus/gulp-mocha#113]
My Mocha test runner is

``` js
gulp.task('test', function () {
  return gulp.src(testSrcFiles)
    .pipe(mocha())
    .on('error', handleError('Mocha'));
});

gulp.task('watchTest', ['test'], () => {
  gulp.watch(testSrcFiles, ['test']);
})
```

`gulp test` works fine
`gulp watchTest` works the first time through, but after a change which triggers the watch I get an error
`Error in plugin 'gulp-mocha' Transport console not attached to this instance`

We use Winston for logging in various parts of the application. In our gulpfile.js it gets imported in through some dependencies.

When I remove any imports inside the gulpfile.js with a dependency on Winston logger, it works fine, but I'm not exactly sure how to resolve the issue.

For completeness, here is our implementation on logger

``` js
import winston from 'winston';
import props from './properties';

const logger = new winston.Logger({
  transports: [
    new winston.transports.Console({ timestamp: true }),
  ],
});

logger.transports.console.level = props.logLevel || 'info';

export { logger as default };
```

We have watch behavior with winston imported on other gulp tasks but do not run into this problem.

Thank you for your time.

**Comment by carloshpds** [comment]
Hi @lifehackett, try to separate your tasks in functions, it works fine to me:
```
function runTests () {
    return gulp.src(options.specFiles, {read: false})
      .pipe(mocha({reporter: 'nyan'})) .on('error', options.errorHandler('Mocha'));
  }

  gulp.task('test', ['scripts'], runTests);

  gulp.task('test:auto', ['watchTests', 'test'], function(){
    return $.watch(options.tmp + '/**/*.js', runTests);
  });
```

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
