### ISSUE TITLE
Fail to read ES6 code with Babel Compiler.

### ISSUE THREAD

**Issue by JulienBonnin-ABTasty** [sindresorhus/gulp-mocha#122]
Hello,

My issue is pretty simple, I am writing my code in ES6 with browserify and babel.

I am trying to configure gulp-mocha before starting to work on my app, but it keeps throwing me an error while trying to parse ES6 code: 

_.each([13, 15], cur => {
                     ^^
SyntaxError: Unexpected token =>

So clearly, it doesn't understand ES6 features. I tried to spcify to gulp-mocha that I'm using Babel, following the documentation by adding this to the top of my gulp-file : 

// DEPENDENCIES FOR MOCHA - COMPILING ES6
require('babel-core/register');

Then here is my task for mocha : 

gulp.task('testing', function () {
	return gulp.src('client/main.js', {read: false})
		// gulp-mocha needs filepaths so you can't have any plugins before it
		.pipe(mocha({
			reporter: 'chai',
			compilers: {
                'js': 'babel'
            }
		}));
});

I tried with and whithout the compilers object, same error in both case :(

Can you help me with that ? Thanks :)

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gulp
Paste in the link to the question here so others can follow ;)

**Comment by Risto-Stevcev** [comment]
@JulienBonnin-ABTasty  `compilers` is not a valid option for the mocha api, so the normal way you would do it (ie: `mocha --compilers js:babel-core/register`) doesn't work. It seems like the README for this project mentions this for Babel:

> Add require('babel/register') to the top of your gulpfile.js.

But that didn't work for me. The [Mocha API](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically) is kind of a joke compared to the CLI options it provides. You could switch to using [gulp-spawn-mocha](https://www.npmjs.com/package/gulp-spawn-mocha), it seems as though this project is going in that direction (see #128).

@sindresorhus Before the project switches to using the binary, it would be useful to get a basic working example (in a folder) for Babel or to elaborate a little bit more on the README FAQ if it's not too much work
