### ISSUE TITLE
Is the readme correct?

### ISSUE THREAD

**Issue by clayreimann** [sindresorhus/gulp-mocha#125]
The readme says that: `// gulp-mocha needs filepaths so you can't have any plugins before it`, however that appears not to be the case based on the `through` code in `index.js`. Is this assertion still correct?

**Comment by sindresorhus** [comment]
Yes, it's still correct: https://github.com/sindresorhus/gulp-mocha/blob/898f748d590d03e0043b23c145fdc9dd63731a3b/index.js#L34

https://github.com/sindresorhus/gulp-mocha/pull/124 could fix it, but I have a feeling it will bring forth a bunch of other issues.
