### ISSUE TITLE
Error Hook but dont execute done hook

### ISSUE THREAD

**Issue by mikeerickson** [sindresorhus/gulp-mocha#127]
Is there a way to execute a method when an error occurs and end the testing operation (but keep alive in watch)

```
  .pipe(mocha())
    .on('error', function(){
        console.log('error')
     })
    .on('end', function(){
      // only get here if all goes well
    });
```

**Comment by mikeerickson** [comment]
Ping

**Comment by Jameskmonger** [comment]
At the moment, the `end` event is triggered at the end of the mocha run - regardless of there being errors or not.

I'd be more comfortable adding an event under a different name to preserve compatibility. Do you have any suggestions for the name @mikeerickson?

**Comment by mikeerickson** [comment]
@Jameskmonger How about 

```
.on('endWithError', function(){
      // only get here if errors occurred but we are done
    });
```

```
.on('endWithoutError', function(){
      // only get here if all goes well
    });
```

Alternately, if you pass an object to the current end with "stats"

```
.on('end', function(resultObj){
      // resultObj would contain overall stats

    });

eg

{
   whatever: data,
   youTracked: data
}
```

**Comment by justinmchase** [comment]
I came here to report this also, it seems to only be an issue for certain kinds of errors such as syntax errors loading the script itself. If there are errors during tests or most other phases it works out.

For example here is an error message that causes the `'end'` event to never be emitted:
```
./lib/dispatcher.js: 'this' is not allowed before super()
```

The code causing the error:
```
export default class Dispatcher extends EventEmitter {
  constructor (nodes, connections) {
    // super() // <-- errors here
    this.nodes = nodes
    this.connections = connections
    this.messages = []
  }
}
```

Here is a workaround I made that is hacky but unblocks me:
```

```js
function test () {
  let ended = false
  let testStream = gulp
    .src('./test/**/*.js', { read: false })
    .pipe(mocha({
      reporter: 'nyan',
      require: ['babel-register']
    }))
    .on('error', (err) => {
      process.stderr.write(`${err.message}\n`)
      setTimeout(() => { if (!ended) testStream.emit('end') }, 50)
    })
    .on('end', () => { ended = true }) // end is not called when a syntax error is in the script

  return testStream
}
```

**Comment by mikeerickson** [comment]
@justinmchase kinda sucky how his has been 10 mos and still no solution.   I *thought* I was clear enough in description but looks like t has received squeaky wheel syndrome.

**Comment by justinmchase** [comment]
From poking around in the code it looks like a `mocha` runner bug to me. We could probably dig into it and come up with a PR there that would fix this.

**Comment by mikeerickson** [comment]
@justinmchase sounds like a plan to me 👍

**Comment by sindresorhus** [comment]
Probably fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
