### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gulp-mocha#128]
I don't have the time or [interest](https://github.com/sindresorhus/ava) in maintaining this anymore.

The Mocha programmatic API has turned out to have so many issues it's pretty much unusable. The next step for anyone willing would be to resolve the open pull requests and then convert the task to [spawn the `mocha` binary](https://github.com/sindresorhus/gulp-mocha/issues/20).

If no one steps up, I'll eventually deprecate this plugin as I'm not doing users any favor of having it go unmaintained.

**Comment by Jameskmonger** [comment]
I'd be interested in maintaining this @sindresorhus. I use mocha in a few of my own projects.

**Comment by najamkhn** [comment]
I can take care of it. Been using gulp and mocha quite frequently now.

**Comment by sindresorhus** [comment]
Thanks for stepping up! You're now collaborator on this repo :)

The guidelines are simple. Be kind to everyone. Larger changes should come in a pull request. Smaller ones can be committed directly. Pull requests should have at least one :+1: from another maintainer before being merged (If there are more than one maintainer excluding me). Follow the existing [code style](https://github.com/sindresorhus/xo) (Tip: `$ xo --fix` can fix many issues) and ensure `npm test` passes before pushing a commit. You can use branches in this repo, but clean them up afterwards. I like a clean commit history, so when merging a pull request, either ask the contributor to [squash](http://stackoverflow.com/questions/11396069/squash-to-only-one-proper-commit-for-github-pull-request) their commits or do it for them manually.

-

Still open to adding more people if you're interested.

**Comment by Jameskmonger** [comment]
Thanks @sindresorhus. Does this give us the ability to publish modules to npm? My npm username is `jameskmonger`.

**Comment by sindresorhus** [comment]
@Jameskmonger Not yet. I'll add you guys there after a grace period :)

**Comment by Risto-Stevcev** [comment]
> The next step for anyone willing would be to resolve the open pull requests and then convert the task to spawn the mocha binary.

Isn't that what [gulp-spawn-mocha](https://github.com/knpwrs/gulp-spawn-mocha) does?

**Comment by sameeri** [comment]
`Be kind to everyone.` @sindresorhus How are you so amazing? I had made you one of my heroes using so much of your code. Your passion for code & open source has always mesmerized me. But just this comment of being kind to everyone has made you my supreme hero in regards to code & conduct. Hopefully i can emulate your love, passion & heart for code. I would have been a silent admirer forever but after seeing those beautiful words, i could not stop myself typing this out. I would love to be your apprentice in anyway possible. <3

**Comment by sindresorhus** [comment]
Closing this as gulp-mocha is now in a good state and I haven't really found anyone suitable to take over.

**Comment by sindresorhus** [comment]
@sameeri That's really nice of you 😊
