### ISSUE TITLE
Incorrect behavior/return code with mocha "after all" hook and failing tests

### ISSUE THREAD

**Issue by treythomas123** [sindresorhus/gulp-mocha#129]
Mocha has "after all" hooks, where you include an "after" at the root level (i.e. not inside a "describe"). I'm seeing some strange behavior when using this in combination with additional things piped after gulp-mocha. Here's a simple example that demonstrates the problem:

**gulpfile.js**

``` js
const gulp = require('gulp');
const mocha = require('gulp-mocha');

gulp.task('test', () =>
    gulp.src('test.js')
        .pipe(mocha())
        .pipe(gulp.dest('./output'))
);
```

**test.js**

``` js
it('should work', function() {
    throw new Error('fail');
});

after('my after hook', function() {
    console.log('after');
});
```

When just executing with mocha (`mocha test`), I see the following output (with return code 1), which seems right:

```
  1) should work
after

  0 passing (8ms)
  1 failing

  1)  should work:
     Error: fail
      at Context.<anonymous> (test.js:2:11)
```

When I run `gulp test` with the above gulpfile, I see the following, with return code 0:

```
[12:40:14] Using gulpfile ~/temp/gulpfile.js
[12:40:14] Starting 'test'...



  1) should work
after

  0 passing (6ms)
  1 failing

  1)  should work:
     Error: fail
      at Context.<anonymous> (test.js:2:11)




  2) "after all" hook: my after hook
```

That last line shouldn't be there, as there was no failure in the `after all` hook.  The return code should also be 1 instead of 0, since the test failed.

I originally found this because I was piping to [gulp-istanbul](https://github.com/SBoudrias/gulp-istanbul) for coverage reports. I had a test failure, but noticed my CI system still continued on as though tests passed, since the return code from gulp was 0.

I tried digging into this a little, and found that the incorrect last line of output is caused by [mocha's error handling](https://github.com/mochajs/mocha/blob/9ae6a85b6ba50ea415affc88456d469d6915a157/lib/runner.js#L293) catching the gulp-plugin error emitted by gulp-mocha when the first test fails. I'm not very familiar with gulp's use of streams yet, so I'm not sure why or how this is getting caught by mocha. It seems like the intent is for it to be caught and handled by gulp itself.

If I comment out the `gulp.dest` line in the gulpfile, or remove the `after all` hook from `test.js`, I get return code 1 and more correct-seeming output. So this issue seems to be somehow caused by the combination of `after all` hooks, and additional things being piped after the call to gulp-mocha.

**Comment by kjvalencik** [comment]
I haven't been able to track down the exact issue yet, but the issue appears to be in `mocha` and not `gulp-mocha`. Using an async after all acts as a work around:

```js
after(cb => {
    /* do stuff */
    setImmediate(cb);
});
```

Pushing the end of the suite to the end of the event loop fixes the problem in `mocha`, but I'm not sure why.

https://github.com/mochajs/mocha/blob/9ae6a85b6ba50ea415affc88456d469d6915a157/lib/runner.js#L638-L639
Wrap that in:
```js
      self.hook('afterAll', function() {
        setImmediate(() => {
          self.emit('suite end', suite);
          fn(errSuite);
        });
      });
```

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
