### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by roymiloh** [sindresorhus/gulp-mocha#133]
[This error](https://github.com/mochajs/mocha/issues/117) appears whenever I use `gulp-mocha` with a watcher (memory increases per `mocha.run`), with mocha's cli (`mocha --watch`) it does not seem to reproduce.

I've tried the current pull requests - it's still happing. The cli itself handles watch a [slightly different](https://github.com/mochajs/mocha/blob/master/bin/_mocha#L343-L397), haven't checked; anyway, it looks like a critical bug.

An example could be _any_ suit case, it just increases as `mocha.run()` is called. Any ideas?

**Comment by roymiloh** [comment]
Well, it was smth with [babel's require hook](https://babeljs.io/docs/usage/require/), which I pass as a plugin to mocha `mocha({ require: ['babel-register'] })`, I _may_ imagine why it didn't work; would you consider it as a bug?

Anyway, the memory still increases, but less then before. I've checked with `mocha --watch` and it increases as well, but less then the current `gulp-mocha` plugin, for any reason.

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
