### ISSUE TITLE
mocha --recursive

### ISSUE THREAD

**Issue by ShavidzeT** [sindresorhus/gulp-mocha#134]
Difference between ```mocha``` command and ```mocha --recursive``` is that recursive argument can test whole tree subdirectories's files. I want to use this argument in gulp-mocha module, is there any where to do it?

**Comment by sindresorhus** [comment]
This plugin is different than the `mocha` binary. Here, gulp takes care of getting the file paths, and this plugin just runs mocha on the file paths it receives. You can easily get files recursively with gulp using the correct glob pattern. Consult the gulp docs for that.
