### ISSUE TITLE
Use mocha -i --invert for inverting grep strings

### ISSUE THREAD

**Issue by lu-c** [sindresorhus/gulp-mocha#136]
Ran into a problem where some of our tests run slowly, and it would be great to be able to exclude them from a run, maybe by adingd '(slow)' to the titles of slow tests. Then we can run gulp-mocha on everything but these identified slow tests. Found that mocha has more an -i / --invert option for grepping that would be useful, and would love if they were implemented to gulp-mocha too!

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
