### ISSUE TITLE
TypeError: Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by Davy-F** [sindresorhus/gulp-mocha#142]
![image](https://cloud.githubusercontent.com/assets/19592376/19803760/69fa71c0-9d02-11e6-921d-cf0f92e4daac.png)

Getting this error when trying to run a test via gulp. Any ideas?

Google hasn't been much help with this particular error.

**Comment by Jameskmonger** [comment]
This isn't an issuue with `gulp-mocha` but is an issue with Angular.

Notice in step 5 of [the Angular Quickstart guide](https://angular.io/docs/ts/latest/quickstart.html), they include `reflect-metadata`.

You need to make sure that script is loaded for your test environment too.

A simple fix would likely be to put `require("reflect-metadata")` at the top of your gulpfile.

**Comment by Davy-F** [comment]
Including require("reflect-metadata") in my gulpfile has seemed to do the trick! Thank you, as I couldn't seem to find any other documentation on this. 

I am now getting a 'sinon is not defined' reference error.
Do I also have to require sinon, or should this already be included in gulp-mocha?
