### ISSUE TITLE
Pipe output to Bunyan

### ISSUE THREAD

**Issue by miparnisari** [sindresorhus/gulp-mocha#145]
Normally, I run my tests with `mocha test/*.js  | bunyan -o short`.

Is it possible to use this plugin and pipe the output to [Bunyan](https://github.com/trentm/node-bunyan#introduction)? Perhaps listening to an event?

**Comment by sindresorhus** [comment]
No, that's not possible. Probably better just to use the `mocha` binary directly in a npm run script.
