### ISSUE TITLE
Stream transpiled files into gulp-mocha

### ISSUE THREAD

**Issue by lambert-velir** [sindresorhus/gulp-mocha#150]
Hi!

I'm trying to `browserify` / `babelify` my files before processing them with `gulp-mocha`, but it's not working.  Something like this:

```javascript
gulp.task("js-test", function() {
    return gulp.src("./**/*.test.js")
      .pipe(transpile({}))
      .pipe(mocha({}));
});


// Create a bundle of the files in the stream using browserify
function transpile(browserifyOptions){

  return through2.obj(function (file, enc, callback){

    // https://github.com/substack/node-browserify/issues/1044#issuecomment-72384131
    const b = browserify(browserifyOptions || {}) // pass options
      .add(file.path) // this file
      .transform(babelify, { presets: ["es2015", "react"] }); // run it through babel, for es6 transpiling

    b.bundle(function(err, res){
      if (err){
        callback(err, null); // emit error 
      }
      else {
        file.contents = res; // assumes file.contents is a Buffer
        callback(null, file); // pass file along
      }
    });

  });
}
```

`.pipe(transpile({}))` doesn't seem to have any effect. It seems that mocha isn't reading the files from the stream, but rather reading the files from the filesystem. 

This works:
```javascript
gulp.task("js-test", function() {
    return gulp.src("./**/*.test.js")
      .pipe(transpile({}))
      .pipe(rename({ extname: ".es6.js" }))
      .pipe(gulp.dest("./"))
      .pipe(mocha({}));
});
```

The problem with this is now I have compiled bundles written to my filesystem that I don't want. 

Is there a ways to get `gulp-mocha` to read the streamed transpiled files without writing them to disk?

**Comment by sindresorhus** [comment]
> .pipe(transpile({})) doesn't seem to have any effect. It seems that mocha isn't reading the files from the stream, but rather reading the files from the filesystem.

Yes, this is documented in the readme:

> gulp-mocha needs filepaths so you can't have any plugins before it

---

> Is there a ways to get gulp-mocha to read the streamed transpiled files without writing them to disk?

Not really. The Mocha API only accepts filepaths.

**Comment by lambert-velir** [comment]
Thanks for the clarification.
