### ISSUE TITLE
Object type mocha options are removed by 'dargs'

### ISSUE THREAD

**Issue by agracio** [sindresorhus/gulp-mocha#155]
Hi,
Version 4.0.1 introduced a bug that causes any mocha options that are of object type to be removed from arguments.
Example gulp task:

```javascript
gulp.task('coverage',  function() {
        return gulp.src(paths.test, {read: false})
            .pipe(mocha({
                'reporter': "mocha-jenkins-reporter",
                'reporterOptions': {
                    "junit_report_name": "Test",
                    "junit_report_path": "JUnit.xml",
                    "junit_report_stack": 1
                }
            }));
});
```
Initially the options in _gulp-mocha_ are:
```
{ colors: true,
  suppress: false,
  reporter: 'mocha-jenkins-reporter',
  reporterOptions:
   { junit_report_name: 'ts-progress',
     junit_report_path: './coverage/JUnit.xml',
     junit_report_stack: 1 } }
```

However after converting options to arguments using  _dargs_ the output is:
```
[ '--colors', '--reporter=mocha-jenkins-reporter' ]
```

**Comment by sindresorhus** [comment]
Per release notes, it's now using the `mocha` binary. So you need to use whatever method the Mocha binary supports to pass reporter options. https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0

**Comment by agracio** [comment]
--reporter-options mocha flag requires additional parameters to be passed to it. Here is an example from Mocha page:
```
--reporter-options output=filename.xml
```
However I do not see how it would be possible to pass such parameters using new version, could you provide an example?

**Comment by sindresorhus** [comment]
`{reporterOptions: 'output=filename.xml'}`

**Comment by agracio** [comment]
This would be become `--reporter-options=output=filename.xml`

**Comment by agracio** [comment]
Is there a planned resolution for this issue? It should not be closed as there is no workaround, so existing functionality is broken.
