### ISSUE TITLE
Downstream tasks aren't firing

### ISSUE THREAD

**Issue by axleonard** [sindresorhus/gulp-mocha#158]
The following configuration worked in 3.0.1: 

```js
gulp.task('mocha', ['pre-test'], (done) => {
    let error;
    gulp.src(paths.unitTests)
        .pipe($.mocha())
        .on('end', () => done(error))
        .on('error', (err) => { error = err; });
});
```

In 4.0.1, the `end` event is never emitted so downstream tasks aren't firing.  The test event, `_result` works, but I imagine that this isn't reliable.

Thanks!

**Comment by sindresorhus** [comment]
Try the `finish` event, although the correct solution would be to return the `gulp.src` instead of using the callback (`done`).
