### ISSUE TITLE
Package now should simply be Renamed, Completely Re-written or Abandoned

### ISSUE THREAD

**Issue by kgentes** [sindresorhus/gulp-mocha#164]
**Issue**: This package no longer has API access to the mocha options. This isn't an architectural improvement. It is a complete failure and abandonment of this wrapper purpose. 

Previously, the usefulness of this package was that it abstracted the `mocha` functionality with its command line options into a gulp accessible API. Hence, `gulp-mocha` .  Now that the newest version of this package has neutered the entire API to require the gulp callers to re-implement their options through the command line, this package has basically 0 value.

If you are going to continue to advertise this package as `gulp-mocha` (the implied "gulp-"ness of a wrapper around mocha) re-implement the API abstraction of the command line options. 

Other than making the root package of mocha callable without options (how useful is that?), the latest major revision (the v4 branch) is all but useless.

**Recommendation**:  Re-implement the API abstraction of the command line options.

**Comment by sindresorhus** [comment]
> This package no longer has API access to the mocha options.

The Mocha API is completely broken. We had more than 20 open unfixable issues because of it.

> Recommendation: Re-implement the API abstraction of the command line options.

It already does that. All your options are converted to command-line arguments for you.
