### ISSUE TITLE
Cannot require multiple files

### ISSUE THREAD

**Issue by bnewcomer** [sindresorhus/gulp-mocha#174]
When setting the require option, using a string (a single file or module path) works fine. However, giving an array of paths causes an error. gulp-mocha converts the array into a single require flag with a comma separated list value, which is not supported by mocha (https://github.com/mochajs/mocha/issues/2250).

`mocha({ require: ['babel-core/register', 'test/setup.js']})`
is converted to
`mocha --require babel-core/register,test/setup.js`
and throws Error: cannot find module 'babel-core/register,test/setup.js'

it should be
`mocha --require babel-core/register --require test/setup.js`

Let me know if there is a plan to fix this or if I am simply using the module incorrectly! Thanks

**Comment by sindresorhus** [comment]
This was already fixed in https://github.com/sindresorhus/gulp-mocha/commit/55004ca98df72446b5c4780d38c216d3cd75f707.
