### ISSUE TITLE
Support the --slow flag

### ISSUE THREAD

**Issue by kevinburke** [sindresorhus/gulp-mocha#177]
From the mocha --help output:

```
    -s, --slow <ms>                         "slow" test threshold in milliseconds [75]
```

I'd like to set this to "2", but it looks like gulp-mocha only passes through a set number of options to the underlying mocha binary.

**Comment by spacem** [comment]
did you try it?
I think this supports all the options.
From the readme:
"Options are passed directly to the mocha binary, so you can use any its command-line options"

**Comment by sindresorhus** [comment]
Yup, supports all the options.
