### ISSUE TITLE
Security Issue: mocha@3.5.3 › growl@1.9.2 allows arbitrary code injection

### ISSUE THREAD

**Issue by subesokun** [sindresorhus/gulp-mocha#180]
As `gulp-mocha` depends still on `mocha@^3.0.0` the NPM security checks (NSP and Snyk) are failing. This issue gets solved by upgrading to `mocha@^4.0.0`. Are there any plans to upgrade Mocha?

[![Known Vulnerabilities](https://snyk.io/test/github/sindresorhus/gulp-mocha/badge.svg)](https://snyk.io/test/github/sindresorhus/gulp-mocha)
https://snyk.io/test/github/sindresorhus/gulp-mocha

**Comment by sindresorhus** [comment]
It's now using Mocha 4
