### ISSUE TITLE
Move mocha to peer dependency

### ISSUE THREAD

**Issue by danthegoodman** [sindresorhus/gulp-mocha#182]
Now that mocha 4 is out, I'd like to start using it. Since this library is now such a thin wrapper around mocha and so that others may continue to use their preferred version of mocha and so that future versions of mocha can be used freely, I propose allowing mocha to be specified as a peer dependency.

I'm not sure whether this needs to constitute a major or minor api version change.

**Comment by danthegoodman** [comment]
I've done some testing with this locally and `gulp-mocha` passes all of its tests when tested against mocha `^2`, `^3` and `^4`. It looks like mocha ^1 fails because it spit out errors to stderr instead of stdout.

**Comment by sindresorhus** [comment]
I don't think a `peerDependency` is a good idea. Mocha might do breaking changes between releases. Better to just upgrade here whenever there's a new Mocha version.
