### ISSUE TITLE
DeprecationWarning: “--compilers” will be removed in a future version of Mocha

### ISSUE THREAD

**Issue by PavelKastornyy** [sindresorhus/gulp-mocha#192]
I run mocha via gulp. This is my code:
```
import mocha from 'gulp-mocha';
...
return gulp.src([testFile], { read: false })
    .pipe(mocha({
        reporter: 'spec',
        compilers: [
            'js:babel-core/register',
        ]
}));
```
The problem is I get this annoying message:

    (node:10357) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info

According to information [here](https://github.com/mochajs/mocha/wiki/compilers-deprecation) I can use --no-deprecation flag. But I can' understand how to add this flag to gulp-moch and could find a way in gulp-mocha package. Can anyone say how to fix it?

**Comment by samsontesfay** [comment]
you can use 'require' instead of 'compilers' option

`import mocha from 'gulp-mocha';
...
return gulp.src([testFile], { read: false })
    .pipe(mocha({
        reporter: 'spec',
        compilers: [
            'js:babel-core/register',
        ]
}));`

**Comment by PavelKastornyy** [comment]
@samsontesfay Thank you very much. Your solution helped.
