### ISSUE TITLE
end event not being triggered after version 3.0.1

### ISSUE THREAD

**Issue by gustavomassa** [sindresorhus/gulp-mocha#194]
Hello,

The mocha "end" event is not being triggered after version 3.0.1.

Based on the readme example:
```
gulp.task('default', () =>
	gulp.src('test.js')
		.pipe(mocha())
		.once('error', err => {
			console.error(err);
			process.exit(1);
		})
		.once('end', () => {
			process.exit();
		})
);
```

On version 3.0.1 end event is emitted.

**Comment by pubkey** [comment]
I have the same problem.

**Comment by KingRial** [comment]
Maybe it's related to https://github.com/sindresorhus/gulp-mocha/issues/108
