### ISSUE TITLE
Version 7.0.0 fails for basic tests

### ISSUE THREAD

**Issue by bgillesp** [sindresorhus/gulp-mocha#196]
`gulp-mocha@7.0.0` fails nondescriptly for a very simple test file.  Running in Node 12.8.0.

Gulp file fragment:

```
function test() {
  return gulp.src('src/test.js', {read: false})
  .pipe(mocha());
}
```

`test.js` consists of only the tutorial test code from https://mochajs.org/#getting-started:

```
var assert = require('assert');
describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
      assert.equal([1, 2, 3].indexOf(4), -1);
    });
  });
});
```

Console output is the following:

```
[20:21:23] Error in plugin "gulp-mocha"
Message:
    There were test failures
Details:
    domainEmitter: [object Object]
    domainThrown: false
```

Expected testing behavior was restored by downgrading to the previous release `gulp-mocha@6.0.0`.

**Comment by bamse16** [comment]
Ran into the same problem, when running on node10.

**Comment by JSanford42** [comment]
I have also encountered this issue on Node 10.16.0. Downgrading to gulp-mocha 6.0.0 runs as expected.

Version 7.0.0 reports test failures exactly as described by @bgillesp. I can run mocha manually and all tests pass.

**Comment by jlenoble** [comment]
I could make testing work again with:

```
const subprocess = execa('mocha', files.concat(args), {
  localDir: __dirname,
  preferLocal: true // LINE ADDED
});
```

According to doc, the default is false (as of execa@2.0.4) and:
- it is not set to true when option localDir is set,
- arrow function getEnv requires it to make actual use of option localDir.
