### ISSUE TITLE
Consider integrating the problems gulp-spawn-mocha had tried to solve

### ISSUE THREAD

**Issue by phated** [sindresorhus/gulp-mocha#20]
The github project seems to have been removed, but from my email:

> I was having problems with the cache, I don't have a link to anything it just seemed like a limitation of the way it was constructed. That try catch statement will get errors but you can still crash the process (e.g., and naively, process.exit(1). Furthermore, if any variables are set outside of modules (e.g., global scope) then those aren't cleared in the existing mocha plugin which I why I said that a new process will always start cleanly.

**Comment by mysterycommand** [comment]
Maybe just consider un-blacklisting [`gulp-spawn-mocha`](https://github.com/KenPowers/gulp-spawn-mocha)? Maybe consider blacklisting your own module (this one)? I know the manifesto says "Your plugin should only do **one thing**, and do it well." and "Your plugin shouldn't do things that other plugins are responsible for", but it seems to me like `gulp-spawn-mocha` does what `gulp-mocha` does and has the features that you seem to be saying `gulp-mocha` needs (a.k.a. does it's thing better).

I'm *really not* trying to be inflammatory. I will fork this and submit a PR if that's the way forward, but  why do the work of porting functionality when `gulp-spawn-mocha` already exists?

Again, I am *really not* trying to be inflammatory. I'm a huge fan of your work and I use your stuff all the time … so … thanks for that. :grin:

**Comment by shellscape** [comment]
@sindresorhus was your intention with the last comment you made that you were going to scrap using mocha as a straight require and instead spawn the process in a cp?

**Comment by sindresorhus** [comment]
@shellscape Yes
