### ISSUE TITLE
Nested orchestrations caused failing tests

### ISSUE THREAD

**Issue by phated** [sindresorhus/gulp-mocha#21]
When trying to use gulp-mocha to run the gulp tests, they would fail due to nested orchestrations (calling `gulp.run` inside a test).

This plugin should do something to avoid those scenarios.  Unfortunately, the only way I can think of right now is to spawn a child process, but I am hoping you can think of a better way.

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
