### ISSUE TITLE
Running mocha is different from running gulp-mocha

### ISSUE THREAD

**Issue by rogierschouten** [sindresorhus/gulp-mocha#41]
My tests were failing with gulp-mocha and passing with mocha. The reason is that when using gulp-mocha, the global namespace does not seem to be cleared between test files. Eventually I resorted to using gulp-exec to call mocha per file, but am I doing something completely wrong or is this something fixable?

**Comment by rails4sandeep** [comment]
This is still an issue. My api tests run perfectly fine when using mocha, but fail when using gulp mocha

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
