### ISSUE TITLE
Get default options from `test/mocha.opts`

### ISSUE THREAD

**Issue by ai** [sindresorhus/gulp-mocha#44]
By default Mocha gets default options from `test/mocha.opts`. This plugin should did it too.

If I need to run only one test, I will execute `mocha test/wrong.js`. But in Travis CI gulp plugin is better. I want to combine this two runner methods, but I need common place to put options,

**Comment by morficus** [comment]
****bump****

any word on having this plugin grab the default options from `test/mocha.opts`? or @floatdrop , could you elaborate on your last comment from above?
it seems like the original intent of this issue got lost with the side conversation :-)

**Comment by thom-nic** [comment]
I was looking for this too.  Unfortunately parsing `test/mocha.opts` is not part of mocha's official API.  The relevant code is in [mochajs/mocha/blob/master/bin/options.js](https://github.com/mochajs/mocha/blob/master/bin/options.js).  Furthermore, it doesn't actually return the parsed options as an object.  Instead it sets `process.argv` :(

So unfortunately I have to agree, mocha should fix this...

**Comment by pierrecle** [comment]
My pull request #119 replies to this need :)

**Comment by denisazevedo** [comment]
#26

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
