### ISSUE TITLE
Mocha Finishes, and then outputs to the console?

### ISSUE THREAD

**Issue by silouanwright** [sindresorhus/gulp-mocha#49]
![Mocha on console](http://imgur.com/sZS7ywC.png)

I have a lot of different outputs. Right now, because Mocha wants to output after it's finished, I have tasks that start after Mocha but end up in the middle of Mocha output.

**Comment by rlouapre** [comment]
@floatdrop in ```1.1.0``` version for which component?

**Comment by floatdrop** [comment]
@rlouapre `gulp-mocha` I think.
