### ISSUE TITLE
Gulp-Mocha fails to exit, but Mocha does

### ISSUE THREAD

**Issue by drundle** [sindresorhus/gulp-mocha#54]
Hi,

I am running a simple test (its failing, but that a separate issue).

Using:

    "gulp-mocha": "^1.0.0",

When I run this using Gulp-Mocha (it happens on Travis as well), it does not exit the testing execution, but when I run this using Mocha, it fails, and exits back to the command prompt.

	var assert = require("assert"),
		elasticsearch = require('elasticsearch'),
		client;

		client = new elasticsearch.Client();
		
		describe(' people', function(){

		beforeEach(function(done){
		  
			//in Gulp Mocha this stops the test runner exiting
			//that this does not work is not this issue.
			client.deleteByQuery({
				index: 'people',
				q: '*'
			}, function (error, response) {
				done();
			});

		   //If i just do done(), it will exit. in both.
		   //done();

		});

		describe('add a entry into the index', function(){
			it('should add Dave as a person to the database', function(done){
				assert.equal(1,1);
			});
		});
	});

**Comment by juanpabloaj** [comment]
If, I use `process.exit()` this kill the `gulp.watch` .

I try with this test code (without database connections) :

https://gist.github.com/juanpabloaj/f1ea60417f47897c940f

``` javascript
describe('app test', function(){
  it('app return json message', function(done){
    request(app)
      .get('/')
      .expect(200)
      .end(function(err, res){
        res.body.message.should.match(/test/);
        done();
      });
  });
});
```

when I use `mocha -w test_app.js`, work fine

``` bash
$ mocha -w test_app.js

  app test
    ✓ app return json message

  1 passing (49ms)

  app test
    ✓ app return json message

  1 passing (13ms)
```

but, If I use `gulp`, only the first time work fine

```bash
$ gulp
[13:04:22] Using gulpfile ~/code/nodejs/gupl-mocha/fail_to_exit/gulpfile.js
[13:04:22] Starting 'watch'...
[13:04:22] Finished 'watch' after 8.98 ms
[13:04:22] Starting 'default'...
[13:04:22] Finished 'default' after 8.52 μs
[13:04:25] Starting 'tests'...


  app test
    ✓ app return json message


  1 passing (23ms)

[13:04:26] Finished 'tests' after 358 ms
[13:04:28] Starting 'tests'...


[13:04:28] 'tests' errored after 154 ms
[13:04:28] Error in plugin 'gulp-mocha'
Message:
    listen EADDRINUSE
Details:
    code: EADDRINUSE
    errno: EADDRINUSE
    syscall: listen
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at EventEmitter.app.listen (/Users/pablo/code/nodejs/gupl-mocha/fail_to_exit/node_modules/express/lib/application.js:559:24)
    at Object.<anonymous> (/Users/pablo/code/nodejs/gupl-mocha/fail_to_exit/server.js:15:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
  app test
    ✓ app return json message


  1 passing (13ms)
```

**Comment by morenoh149** [comment]
@juanpabloaj I'm no expert on testing. But it sounds like you could recreate the mocha object for every test. This would also help isolate issues. Could you try that?

**Comment by felipe-pereira** [comment]
In my case I create a child process on server.js (a simple scheduler), added ```process.exit()``` as suggested, but it was useless since on-error or on-end are never called.

**Comment by AndrewSouthpaw** [comment]
I tried the `mongoose.connection.close()` option, but `gulp mocha` would still hang.

The problem with `process.exit()` for me is that I can't reach any tasks in a sequence following `mocha`. This is problematic when I want to, say, run `coveralls` afterwards. Has anyone found a different workaround?

**Comment by gaastonsr** [comment]
How do you run your tests? You might do something like

    gulp test; coveralls

**Comment by AndrewSouthpaw** [comment]
Hmm, that's an interesting idea. Ultimately, I'm using Coveralls for Travis, so I placed an extra command in the `.travis.yml`:

```
after_script:
 - ./node_modules/.bin/gulp coveralls
```

That did the trick alright.

Still, something doesn't seem right with me about needing a workaround like that. I wish I could figure out the root problem.

**Comment by richardschneider** [comment]
Using [gulp-spawn-mocha](https://www.npmjs.com/package/gulp-spawn-mocha) fixes the problem for me.

**Comment by brandon-collins** [comment]
I was having a similar issue, i.e. my test run and all pass, all done callback called but mocha was not exiting as I'd expect it to. The solution was that I had an unexpected option defined in my global mocha.opts file.

--no-exit

removing the above solved my issue.

**Comment by justinr1234** [comment]
Fixed for me: https://github.com/dreame4/gulp-exit

**Comment by suplo** [comment]
@juanpabloaj I have the same problem as you with asynchronous tests (in my case I used request to test a Rest API). By rewriting the test as

```
  var check = function(done, f) {
    try {
      f();
      done();
    } catch (e) {
      done(e);
    }
  };

  it('should validate', (done) => {
    check(done, () => {
      request.post(url, { form: data }, (err, response, body) => {
         // do some assertions
      });
    });
  });
```
the test passed for both single-run and gulp-mocha (watching mode)

Ref https://stackoverflow.com/questions/11235815/is-there-a-way-to-get-chai-working-with-asynchronous-mocha-tests?answertab=active#tab-top

**Comment by lohith-s** [comment]
I have my gulpfile.babel.js like this:
import gulp from 'gulp';
import path from 'path';
import grommetToolbox, {getOptions} from 'grommet-toolbox';
import babel from 'gulp-babel';
import mocha from 'gulp-mocha';
import jsxCoverage from 'gulp-jsx-coverage';

const opts = getOptions();

const jsxCoverageOpts = {
  src: opts.componentTestFiles || [],
  isparta: true,
  istanbul: {
    preserveComments: true,
    coverageVariable: '__MY_TEST_COVERAGE__',
    exclude: /node_modules|test|icons|lib|index/,
    include: /\.js?$/
  },
  transpile: {
    babel: {
      include: /\.js?$/,
      exclude: /node_modules/
    }
  },    
  coverage: {
    reporters: ['text', 'json','lcov'],
    directory: 'coverage'
  }
};

gulp.task('watch', function() {
  gulp.watch(['src/**', 'lib/**', 'test/**'], ['mocha']);
});

gulp.task('mocha', function () {
  jsxCoverage.initModuleLoaderHack(jsxCoverageOpts);
  return gulp.src(opts.componentTestFiles)
    .pipe(babel())
    .pipe(mocha({enableTimeouts: false, timeout: 10000, require: ['./test/js/components/0_setup.js']}))
    .once('end', jsxCoverage.collectIstanbulCoverage(jsxCoverageOpts))
    .once('error', function(err) {
	  if (err !== undefined && err.message !== undefined && err.message.indexOf("failed") > -1) {
	    console.log("Error :: " + err.message);
	    process.exit(1);
	  } else {
	    console.log('End :: Test coverage report available at coverage/lcov-report/index.html');
	    this.emit('end');
	  }
    });
});

gulp.task('dev-test', ['mocha', 'dev']);

gulp.task('dist-test', ['mocha', 'dist']);

grommetToolbox(gulp, opts);



Its working for me locally when i do mvn clean install.

But in Jenkins, when i intentionally fail a test case and run a build, jenkinsis hanging and doesnt come out....Any help appreciated..

**Comment by Wtower** [comment]
This issue still persists. Valid workarounds are gulp-spawn-mocha by @richardschneider and gulp-exit by @justinr1234.

**Comment by Wtower** [comment]
Based on the [comment in this same issue](https://github.com/sindresorhus/gulp-mocha/issues/1#issuecomment-55710159) this is my mocha task:

```
  mocha: function () {
    gulp.doneCallback = function (err) {
      process.exit(err ? 1 : 0);
    };
    return gulp.src(paths.mocha)
      .pipe(plumber())
      .pipe(mocha({reporter: 'spec', colors: true}))
      .on('error', handleError('Mocha'))
      .pipe(istanbul.writeReports());
  },
```

**Comment by dbellavista** [comment]
Personally I require mongoose to connect on begin and disconnect when all tests are finished. So in every test I require:

```
require('./test-setup');
```
```
// test-setup.js
const chai = require('chai');
/* setup chai */
const mongoose = require('mongoose');
before(done => mongoose.connect('<mongo-connection-string>', done));
after(done => mongoose.disconnect(done));
```
