### ISSUE TITLE
How can i pass globals module?

### ISSUE THREAD

**Issue by violet-day** [sindresorhus/gulp-mocha#70]
I tried [mocha-test-runner-with-gulp](https://github.com/gulpjs/gulp/blob/master/docs/recipes/mocha-test-runner-with-gulp.md).But it not work for me.

**Comment by eipark** [comment]
This seems to be broken for me as well. I'm trying something like

```
gulp.src('file', {read: false})
   .pipe mocha
         reporter: 'list'
         globals:
             foo: 'bar'
```

and in my test file, printing `global.foo` is undefined.

**Comment by sindresorhus** [comment]
No idea what you're asking. Please try to do an effort when you open an issue. This is also better asked on StackOverflow ;)

**Comment by mmahalwy** [comment]
Yeah I cannot get globals to work either
