### ISSUE TITLE
Gulp 4.0 mocha doesn't run tests

### ISSUE THREAD

**Issue by ilanbiala** [sindresorhus/gulp-mocha#74]
Mocha doesn't actually seem to run the tests when using the latest commit in the Gulp 4.0 branch. It just logs `Starting 'mocha'` and then exits.

Sample code:
```
function mochaTest() {
	gulp.src([
			'app/**/*.js',
			'config/**/*.js',
			'public/modules/**/*.js'
		])
		.pipe(istanbul())
		.on('finish', function() {
			var server = require('./server');

			return gulp.src('./test/**/*.js')
				.pipe(mocha({
					// reporter: 'mocha-lcov-reporter'
				}))
				.pipe(istanbul.writeReports())
				.once('end', function() {
					server.kill();
				});
		});
}
```

`require('./server')` auto-starts the server and I just kill it at the end once mocha has run. This worked with 3.8.10, but with Gulp 4.0 no tests are actually run.

**Comment by ilanbiala** [comment]
@sindresorhus any ideas on what will fix this issue?

**Comment by ilanbiala** [comment]
Is anyone else having an issue using gulp-mocha with Gulp 4, or is it something with gulp-istanbul?

**Comment by ilanbiala** [comment]
It seems that the issue may actually lie with gulp-istanbul for anyone who also runs into this issue.

**Comment by gbahamondez** [comment]
@ilanbiala  in which OS are you running , currently for me on MacOSX Node 5.7.1 is working  just fine (including istanbul)

**Comment by ilanbiala** [comment]
Are you using Gulp 4?

**Comment by ilanbiala** [comment]
https://github.com/HTHS/hths-lunch/blob/master/gulpfile.js#L141

**Comment by gbahamondez** [comment]
@ilanbiala  Mmm sorry no idea what's the error about your gulp file, since i don't have time to debug it now, but i created a [really simplistic  sample](https://github.com/gbahamondez/gulp4-test) for you , using gulp 4 , gulp-mocha  and  gulp-istanbul, which demostrate that all is working fine, take a look :D.

**Comment by ilanbiala** [comment]
Maybe just a newer version of Gulp fixed it. Thanks!
