### ISSUE TITLE
Requiring any non-server file causes tests to fail

### ISSUE THREAD

**Issue by tyrw** [sindresorhus/gulp-mocha#75]
I have a very basic test set running, and if I `require` any file other than my `test_server.coffee` file in my gulpfile, the test suite fails.  This works just fine:

```
gulp     = require 'gulp'
mocha    = require 'gulp-mocha'

gulp.task 'mocha', () ->
  gulp.src './test/*.coffee', { read: false }
    .pipe mocha
      reporter: 'nyan'
      globals: should: require 'should'
```

But this will break all the tests:

```
gulp     = require 'gulp'
mocha    = require 'gulp-mocha'
foobar   = require './path-to-file-that-exists'

gulp.task 'mocha', () ->
  gulp.src './test/*.coffee', { read: false }
    .pipe mocha
      reporter: 'nyan'
      globals: should: require 'should'
```

This causes `require` statements in my test suite to return `undefined`, and that subsequently causes tests to fail, e.g.: `TypeError: Cannot call method 'setup_test_db' of undefined`.

The `mocha` command will run the test suite just fine either way; it is only the `gulp mocha` command that causes the error.

Any ideas on if this is a bug and how to fix?

**Comment by jreading** [comment]
You need to stub out the require statements in the required in modules using something like proxyquire. See [this](http://stackoverflow.com/posts/11770201/revisions) stackoverflow comment.

**Comment by kevva** [comment]
@twler, did you have any luck with this using proxyquire?

**Comment by twler** [comment]
@kevva I haven't revisited this problem, but looks like I just didn't include anything external like I had originally planned.  Have not tried proxyquire.

**Comment by sindresorhus** [comment]
Try out the latest version: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
