### ISSUE TITLE
Exit code 1 not used on errors

### ISSUE THREAD

**Issue by mgartner** [sindresorhus/gulp-mocha#76]
I realize #45 has been closed and locked, but I do not believe this issue has been fixed. I am unable to get gulp-mocha to exit with anything other than exit code 0. I'd love to contribute a patch to fix this if anyone can point me in the right direction here.

Here's what I'm doing:

```js
gulp.task('test', function (done) {
  gulp.src(testFiles)
  .pipe(require('gulp-mocha')({ reporter: 'spec' }))
  .on('error', console.log)
  .on('end', done);
});
```

**Comment by neoziro** [comment]
@mgartner take a look to #77

**Comment by mgartner** [comment]
Unfortunately the solution mentioned in the README does not work. It will exit with code 1, but it does not allow the tests to fully finish.

As observed in the following example: https://github.com/mgartner/gulp-mocha-exit-test

Calling the `done` callback correctly ends with the message:

```
[14:42:03] Finished 'test1' after 43 ms
```

With `process.exit()`, that message is never displayed because the process exits prematurely.

Please reopen this issue as it has not been solved.

**Comment by neoziro** [comment]
@mgartner aggreed, I don't use this module because it doesn't work properly, so I run test using mocha command directly
