### ISSUE TITLE
Mocha as peer dependency

### ISSUE THREAD

**Issue by abiee** [sindresorhus/gulp-mocha#78]
I want to use peerigon/xunit-file plugin to generate xunit reports, but it depends on mocha. I have to install two versions of mocha.

    node_modules
        ├── gulp-mocha
        │   └── node_modules
        │       └── mocha@2.0.1
        └── mocha@2.1.0

Why not to put mocha as peer dependency instead?

**Comment by sindresorhus** [comment]
Nope. I don't have the time to yet again explain why peerDepdencies are bad, but Google it. You can `npm dedupe` to make that one. npm will do that by default in 3.0.
