### ISSUE TITLE
Adding gulp-mocha to a task causes gulp to never exit (even though mocha's task was completed successfully)

### ISSUE THREAD

**Issue by MadaraUchiha** [sindresorhus/gulp-mocha#82]
I have the following in my gulp file:

```js
gulp.task('lint', function() {
    // ...
});

gulp.task('test', function () {
    require('6to5/register');
    return gulp.src('test/**/*.js', {read: false})
        .pipe(mocha({reporter: 'spec'}));
});

gulp.task('default', ['lint', 'test'], function() {
    console.log('\n\n\nCompleted successfully!');
});
```

When running `gulp`, everything runs correctly, I get the "Completed succesfully" message, but the process doesn't exit. When I remove `test` from the list of dependencies for `default`, it exists as expected. (For comparison, removing `lint` had no effect).

I found gulpjs/gulp#416 but that was fixed several minor versions ago, and the last comment there indicates that the problem is likely to be with one of the plugins.

**Comment by sindresorhus** [comment]
This is already documented in the readme. Please read it.

https://github.com/sindresorhus/gulp-mocha#test-suite-not-exiting

**Comment by MadaraUchiha** [comment]
Indeed it is. Shame on me, shame on my family, shame on my cow, shame on my...

**Comment by IanVS** [comment]
Unless I'm doing something else wrong, the documented solution does not work well if the task can be run either with or without a watch.  My use case is that I have a gulp task (`script-test`), which is run as a watched task when I am developing, but could also be run directly through an npm script (`test: "gulp script-test"`).

Adding `.once('end', () => { process.exit(); });` works fine to end the process after testing completes when run with `npm test`, but it kills the watch when I'm running it as a part of the larger suite.  Is there anything else I can do other than add in a test to determine if watch is running?  That seems very hacky.  Any other suggestions?

**Comment by andreyselitsky** [comment]
Guys, process.exit is not an answer.

If I have a chain of gulp tasks and one of them gulp-moch which does process.exit - the rest of the tasks is not starting....

**Comment by demisx** [comment]
Passing `{exit: true}` is what worked for me with mocha 5.x:

```js
gulp.task("request", () =>
  gulp
    .src(paths.request, {
      read: false
    })
    .pipe(
      mocha({
        env: {
          NODE_ENV: "test"
        },
        reporter: "dot",
        bail: true,
        exit: true,
      })
    )
)
```
