### ISSUE TITLE
Add option for compilers flag or explicitly state how to specify this in the docs

### ISSUE THREAD

**Issue by jxm262** [sindresorhus/gulp-mocha#84]
Sorry if this is the wrong place to ask this, but can we add something for the mocha --compiler flag?  I tried looking through the source and couldn't easily figure out how to explicitly set this option.  However, when I just do add a require('mycompiler') at the top of my gulpfile, it somehow magically runs during the mocha task.  I see the readme explains how to do this for coffeescript, but I have my own compiler which I use for jsx to js transormations (reactjs).    

For example, running from the command line  `mocha --compilers .:my_compiler.js test/**/*.js`

**Comment by hsunami** [comment]
+1

**Comment by gagoman** [comment]
Mocha doesn't support programmatic set of compiler, so you can do something like `babel/register` or `coffescript/register`

**Comment by eddiemoore** [comment]
:+1:

**Comment by kevva** [comment]
Just `require` it manually in your `gulpfile.js`.

**Comment by KunalKapadia** [comment]
You can pass compilers options as per [this!](http://stackoverflow.com/a/30554448/825980) stackoverflow answer.
