### ISSUE TITLE
gulp-mocha break the pipe spirit

### ISSUE THREAD

**Issue by GammaNu** [sindresorhus/gulp-mocha#88]
For minimalist test file, my gulpfile insert on the flow the production code at the beginning of the corresponding test file.

`dummy.coffee` will be concatenated before `dummy_test.coffee`
`any.coffee` will be concatenated before `any_test.coffee`
but gulp-mocha open file by name and don't use the pipe modified content...
That's why i need to break the pipe with temp files as extra step.

gulp-mocha could use `file.content` if present and only load it from filesystem file if `read:false` have been used. I think this behavior more intuitive.

As example, my actual gulpfile.
``` coffeescript
gulp = require 'gulp'
$ = require('gulp-load-plugins')()
del = require 'del'

chemins =
  tests: 'src/**/*_test.coffee'
  tmp: 'tmp/'

gulp.task 'test', ->
  gulp.src(chemins.tests,
#    read: false
  )
  .pipe($.wrapper(
      header: (file)->
        filename = file.path.split('/').pop().split('\\').pop()
        "@@include('"+filename.replace(/_test/, '')+"')\n"
  ))
  .pipe($['fileInclude']())
  .pipe(gulp.dest(chemins.tmp+'test/'))
  gulp.src(chemins.tmp+'test/**/*.coffee',
    read: false
  )
  .pipe($.mocha(
      reporter: 'spec'
      globals:
        should: require('should')
    ))
```

**Comment by kevva** [comment]
Mocha doesn't support creating tests based of file contents. It needs the filepath.
