### ISSUE TITLE
Support of mocha's `require` option

### ISSUE THREAD

**Issue by tdeekens** [sindresorhus/gulp-mocha#90]
Cheers for this task. I am just trying to move things from `grunt` to `gulp` but am struggling with integrating the `require`-option from mocha which is also offered in the `grunt-mocha-test`-task.

Is there a way of using this option? Would it need some work on the task?

**Comment by j-hannes** [comment]
:+1:

**Comment by j-hannes** [comment]
I quickly checked [mocha](https://github.com/mochajs/mocha) but couldn't find any hints for supporting a require option in the node api.

[Gulp-spawn-mocha](https://github.com/KenPowers/gulp-spawn-mocha) supports a `require` (or `r`) option.

For now a quick (and dirty...) workaround might be this:

```JavaScript
.pipe(mocha({
  reporter: 'min',
  globals: {
    env: require('./test/setup')
  }
}))
```
which works but is essentially including the module already in the gulp file...

**Comment by kevva** [comment]
@j-hannes, https://github.com/mochajs/mocha/blob/master/bin/_mocha#L74.

**Comment by kevva** [comment]
Just `require` it manually in your `gulpfile.js`. Mocha doesn't have this as a programmatic option because it's super easy to just do it yourself.

**Comment by kpdecker** [comment]
@kevva Isn't the issue here that requires that need access to `before`, `after`, etc won't have those instantiated?

**Comment by kpdecker** [comment]
https://github.com/mochajs/mocha/blob/master/bin/_mocha#L307 occurs after the mocha instance and most importantly UIs have been setup.

https://github.com/sindresorhus/gulp-mocha/blob/master/index.js#L8-L24 has no injection point
