### ISSUE TITLE
How to output HTMLCov to a file?

### ISSUE THREAD

**Issue by unbug** [sindresorhus/gulp-mocha#91]
``` js
gulp.task('test:android', function(){
  return gulp.src('android-*.js', {read: false})
    .pipe($.mocha({ui:'bdd',reporter: 'html-cov'}))
    .pipe(gulp.dest('./reports.html'));
});
```

In this case,I can only see the result in the console log,do I miss something?

**Comment by Brasilikum** [comment]
+1

**Comment by flancer64** [comment]
+2

**Comment by flancer64** [comment]
Thanks, [Ashwell](http://stackoverflow.com/a/28122171/4073821):

	gulp.task('test', function () {
		var output = './build/TESTS.md'
		// clear out old coverage file
		fs.writeFileSync(output, '')
		// if you still want to see output in the console
		//   you need a copy of the original write function
		var ogWrite = process.stdout.write;
		process.stdout.write = function (chunk) {
			fs.appendFile(output, chunk);
			// this will write the output to the console
			ogWrite.apply(this, arguments);
		};

		return gulp.src('src/**/*.spec.js', {read: false}).pipe(mocha({reporter: 'markdown'}))
	})

**Comment by Talento90** [comment]
That is not a elegant solution specially because it's not supposed to write the last line. But at least is a solution :+1:

**Comment by ErikSchierboom** [comment]
+1

**Comment by sindresorhus** [comment]
Try out the latest version: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0 You can now just use the normal Mocha flags to achieve this.

**Comment by unbug** [comment]
@sindresorhus Thanks
