### ISSUE TITLE
mocha task under watch only runs twice

### ISSUE THREAD

**Issue by skarfacegc** [sindresorhus/gulp-mocha#96]
No failures are being emitted (so I'm not even at the point of needing to deal with plumber)

opened a similar issue ( https://github.com/gulpjs/gulp/issues/1109 ) on gulp, opening here just in case

- Touch a file that matches the watch glob, test runs correctly
- touch the same file, tests runs correctly
- touch the same file, test does **not** run
- touch another file that matches the watch glob, test runs
- touch that file again, test does **not** run

OSX 10.10.3 / gulp 3.9.0 / gulp-mocha 2.1.1
my gulpfile

    'use strict';

    var gulp = require('gulp');
    var mocha = require('gulp-mocha');

    gulp.task('test', function() {
        gulp.src('test/unit/**/*.js')
            .pipe(mocha());
    });

    gulp.task('watch', function() {
        gulp.watch('lib/**/*.js', ['test']);
    });

**Comment by skarfacegc** [comment]
figured it out.  I was using sinon.useFakeTimers and forgot to reset one.

**Comment by arthurvr** [comment]
Glad you figured it out.
